services:
  postgres:
    image: postgres:15
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - data-net
    restart: always

volumes:
  postgres_data:

networks:
  data-net:
    external: true
